# Collect Data
0 8 * * * /bin/bash /home/automation/collect.sh
0 12 * * * /bin/bash /home/automation/collect.sh
0 15 * * * /bin/bash /home/automation/collect.sh

# Cleanup
0 0 * * * /bin/bash /home/automation/cleanup.sh